### ISSUE TITLE
 5.1 Various GUI bugs

### ISSUE THREAD

**Issue by Sylphe** [hadouken/hadouken#159]
Played with it for a bit:

Up and down speeds are inverted 

Pause does not seem to be responding.

Change of folder tab while adding new torrent doesn't work (or should it ? other option is .json file)

And also you probably already know but the advanced tab in settings returns blank

Awesome job btw

**Comment by vktr** [comment]
The pause-button. All torrents are auto managed by libtorrent (by default). When they are auto managed, libtorrent handles any pausing/resuming. Therefore it probably decides to resume the torrent again when pausing (since it has not met the default seed goals). The way around this is to double click the torrent an uncheck the *auto managed* checkbox. Then you can pause again :) I'm currently thinking of a better way of handling this. I can unset auto managed right before pausing, for example.

I'm not sure I understand the folder tab thing problem. Can you elaborate?

Advanced settings returns blank since I haven't thought of any advanced settings to put there. I'll probably think of something someday.

Great input :)

**Comment by Sylphe** [comment]
add a torrent > Path.  normally you should be able to change from default path that you configure when you install hadouken . I beleive the drop down menu would be showing the list of available drives and you could then set your new path for this torrent specifically. The default still being only modifiable with the .json file. 

The advanced settings tab normally should show the advanced libtorrent settings that were also present in the V4 iterations. It would be nice if you could bring them back,when you have time of course, since it allows scaling of libtorrent performance to suit the machine/connection speed.

**Comment by vktr** [comment]
Ah, I see. I changed the behavior for the dropdown. Now it will show the default download directory and any other directories you add to your configuration. If you add `bittorrent.downloadDirectories` to your JSON configuration, like this,

```
{
  "bittorrent":
  {
    "downloadDirectories":
    [
      "C:/Temp",
      "E:/Movies"
    ]
  }
}
```

The add torrent dialog would show these two directories below your default download directory.

I'm planning on adding UI support for configuration in the near future. Then I'll add advanced settings as well.
