### ISSUE TITLE
Force rechecking a paused unmanaged torrent issue.

### ISSUE THREAD

**Issue by zp** [hadouken/hadouken#177]
If you attempt to do a force recheck on a paused torrent that has data in its directory and "Auto Managed" unchecked, it will sit on 0% checked until you re-enable the "Auto Managed" option for that particular torrent.

1. Add torrent
2. Let it download some data.
3. Uncheck Auto Managed in torrent properties.
4. Pause.
5. Force recheck.

It will also happen when you add a new torrent that already has partial or complete data, if you selected the paused option when adding it.

Not sure if this is the intended behavior, I would expect it to recheck the paused torrent, then return to the paused state. (when you set auto managed back on to complete the recheck, it seems to go back to an active state)

Rechecking an active (downloading or seeding) "unmanaged" torrent appears to work fine, will recheck then go back to the download/seed state.

**Comment by vktr** [comment]
Thanks, I'll investigate!

**Comment by vktr** [comment]
Did some testing. The "problem" is that the torrent is paused (and not auto managed) when you force a recheck. The paused state is kept when it goes into checking. One bug I found is that the Start/Resume-button is disabled when a torrent is paused/checking.

I'll fix your expected behavior - force checking a paused torrent which is not auto managed will start a force recheck, resume it, and when the recheck is complete, it will return the torrent to a paused state.

**Comment by therist** [comment]
Hi I just ran into this problem, with version 5.2.0. Has this problem been fixed so far? Thank you

**Comment by RogerGMartins** [comment]
same issue for me on 5.2.0.
