### ISSUE TITLE
64-bit

### ISSUE THREAD

**Issue by ghost** [hadouken/hadouken#228]
Currently only 32-bit releases are offered

**Comment by Robo210** [comment]
Are you currently running into scenarios where Hadouken is running out of available address space as a 32-bit process, or are running in a 64-bit Linux or Windows Server Core environment without 32-bit support installed?

**Comment by svnpenn** [comment]
Obvious troll spotted

**Comment by svnpenn** [comment]
![](http://www.quickmeme.com/img/c8/c8e3349386722dfa0a67ab9b7d9ed8661ff79198d331ed1dbdb92503df1b19ce.jpg)

**Comment by vktr** [comment]
Hi @svnpenn! Quite an unnecessary comment, however to answer your question - the drawbacks (if you can call them that) to releasing both x86 and x64 versions of Hadouken are greater than the wins IMHO. There's the double build, double testing, etc.

There is some emulation involved when running 32-bit applications on 64-bit Windows (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa384249(v=vs.85).aspx) but I haven't had a situation where Hadouken has ran into any problems because of that.

For another project of mine ([PicoTorrent](https://github.com/picotorrent/picotorrent)) I started out with only releasing 64-bit versions, but after some user feedback decided to release 32-bit versions as well. In hindsight, it might have been better to only to 32-bit releases to avoid the double build and double test scenario.

When targeting x86, 100% of users are able to run the application without problem. When targeting x64, some users might be left out (even though they are a small group).

So, to answer your question - I'd rather avoid the work and just target x86 to get to 100% of the user base :smile:

**Comment by svnpenn** [comment]
https://github.com/frostwire/frostwire/issues/199

**Comment by svnpenn** [comment]
https://github.com/irzyxa/Volume2/issues/3

**Comment by svnpenn** [comment]
https://github.com/malensek/3RVX/issues/73

**Comment by svnpenn** [comment]
https://github.com/visualfc/liteide/issues/883
