### ISSUE TITLE
Configure DHT

### ISSUE THREAD

**Issue by vktr** [hadouken/hadouken#94]
Add a way of enabling/disabling DHT.

**Comment by zbuttram** [comment]
Super need this, certain trackers require DHT disabled.

**Comment by zapotah** [comment]
Could this be implemented in the next release? We only need to use the client locally and having DHT connections is causing issues with the IT-administration.

**Comment by vktr** [comment]
I'll add a configuration setting in the `config.json` file for v5. It will be enabled by default.

Sounds OK?

**Comment by zapotah** [comment]
Sounds good. This is for the MS academy sccm scenario i described in the groups discussion about a month ago. I cannot deploy until i can disable DHT since it will exhaust the NAT pool with ~200 clients. :) Any ETA or a vague guess if v5 will be released before june? (That is when my contract with the uni ends and i would love to test this before that)

**Comment by vktr** [comment]
I see. I'll probably release v5 sometime in the first half of april. It is quite stable now, however, if you want to try a pre-release.

The pre-configuration part has changed. I'll write something up in the wiki and let you know.
